### PR TITLE
Created navigation component

### PR DESCRIPTION
**Pull request by pritam-kr**
Created navigation basic component 

Screenshot (155)

### CODE REVIEW

**Review by srishti-maurya — APPROVED** [review]
This looks amazing 👍

**Review by jeetsdev — APPROVED** [review]
Looks good 💯

**Review by himadri2110 — APPROVED** [review]
Good to go.

**Comment by pritam-kr** [comment]
Thank you @srishti-maurya @jeetsdev @himadri2110  for review.

**Pull request merged**
