### PR TITLE
Created first component Alert 

### PR DESCRIPTION
**Pull request by pritam-kr**
- I added only components, a code snippet, and a little bite of documentation about it.

### CODE REVIEW

**Review by srishti-maurya — APPROVED** [review]
This looks amazing!

**Review by kshitijthatte — APPROVED** [review]
Looks great!

**Comment by vijaytembugade** [comment]
perfect color combinations!

**Comment by pritam-kr** [comment]
Thank you @vijaytembugade @srishti-maurya @kshitijthatte

**Pull request merged**
