### PR TITLE
Created card component

### PR DESCRIPTION
**Pull request by pritam-kr**
Created card components with different types

-Text Cards
- Vertical Cards with image
- vertical Card With Text Overlay
- Vertical Card With Badge
-  Horizontal Card

Screenshot (132)

Screenshot (133)

Screenshot (134)

Screenshot (135)

Screenshot (136)

### CODE REVIEW

**Review by poornima-alugubelly — APPROVED** [review]
Good to go!

**Comment by Swapnilkota108** [comment]
Looks good

**Review by SJTGSHIVAM — APPROVED** [review]
Everything looks good just try to maintain a design pattern as discussed. Rest we looks good to merge.

**Comment by saifudinbadani** [comment]
looks good to merge. very well done

**Pull request merged**
